Update vapor-beta.rb to include latest toolbox release
vapor/homebrew-tap pull request #30
Opened 2020-04-08 03:37 UTC by rpstro02

Revved vapor beta toolbox version

2020-04-16 13:51 UTC, tanner0101 requested changes

2020-04-16 13:51 UTC, tanner0101 commented on vapor-beta.rb
>      sha256 "3f031f885fc4cfac9cabb6cb86124ad1283cd75ce58bc5804774c04af45e6d03"
The sha256 hash should need to be changed here

2020-06-12 02:29 UTC, JamesCoonce commented
Is there an update on this?

2020-06-17 09:38 UTC, 0xTim commented
This has been supersceded by Beta 29

2020-06-17 09:38 UTC, closed without merging